- item-types:
    - docker-container
  fields:
    namex:
      path: $.[0].Name
    state:
      path: "$.State"
      map:
        "exited": stopped
        "PowerState/stopped": stopped

- item-types:
    - docker-image
  fields:
    repo_tag:
      path: $.[0].RepoTags[0]
