#
# docker run
#
- type: terminal
  item-types:
    - docker-image
  name: Create container from this image
  cmd: docker run ${id}
  refresh: parent

#
# delete image
#
- type: delete
  item-types:
    - docker-image
  name: Delete
  cmd: docker image remove ${id}
  refresh: parent

#
# prune containers
#
- type: delete
  item-types:
    - docker-container-list
  name: Prune stopped containers
  cmd: docker container prune
  interactive: true
  refresh: self

#
# delete container
#
- type: delete
  item-types:
    - docker-container
  name: Delete
  cmd: docker container remove ${id}
  refresh: parent


#
# start container
#
- type: start
  item-types:
    - docker-container
  name: Start
  cmd: docker container start ${id}
  refresh: self
  when:
    path: $.State
    value: exited

#
# stop container
#
- type: stop
  item-types:
    - docker-container
  name: Stop
  cmd: docker container stop ${id}
  refresh: self
  when:
    path: $.State
    value: running

#
# pause container
#
- type: pause
  item-types:
    - docker-container
  name: Pause
  cmd: docker container pause ${id}
  refresh: self
  when:
    path: $.State
    value: running

#
# unpause container
#
- type: unpause
  item-types:
    - docker-container
  name: Unpause
  cmd: docker container unpause ${id}
  refresh: self
  when:
    path: $.State
    value: paused

#
# restart container
#
- type: restart
  item-types:
    - docker-container
  name: Restart
  cmd: docker container restart ${id}
  refresh: self
