#
# delete image
#
- type: delete
  item-types:
    - docker-image
  name: Delete
  cmd: docker image remove ${id}
  refresh: parent

#
# delete container
#
- type: delete
  item-types:
    - docker-container
  name: Delete
  cmd: docker container remove ${id}
  refresh: parent

#
# start container
#
- type: start
  item-types:
    - docker-container
  name: Start
  cmd: docker container start ${id}
  refresh: self

#
# stop container
#
- type: stop
  item-types:
    - docker-container
  name: Stop
  cmd: docker container stop ${id}
  refresh: self

#
# pause container
#
- type: pause
  item-types:
    - docker-container
  name: Pause
  cmd: docker container pause ${id}
  refresh: self

#
# unpause container
#
- type: unpause
  item-types:
    - docker-container
  name: Unpause
  cmd: docker container unpause ${id}
  refresh: self

#
# restart container
#
- type: restart
  item-types:
    - docker-container
  name: Restart
  cmd: docker container restart ${id}
  refresh: self
