- item-types:
    - docker-image
  cmd: docker image inspect ${id} --format json
  refresh: self

- item-types:
    - docker-container
  cmd: docker container inspect ${id} --format json
  refresh: self

- item-types:
    - docker
  cmd: docker info --format json
  refresh: self
