- type: dropdown
  name: Select Container
  items: []
  source:
    cmd: |
      docker container list --format json
    parser: rows-json
    path-id: $[*].ID
    path-name: $[*].Names
  produces:
    - variable: container_id
