type: layout-form
id: root
form:
  - type: section
    subitems:
    - type: row
      subitems:
        - $include: docker/__docker_image_selector_field.yaml
        - $include: docker/__docker_container_selector_field.yaml
