type: layout-form
id: root
form:
  - type: section
    subitems:
      - type: link-row
        text: Read Getting Started Guide to learn more details on registering and configuring your UpCloud account
        link: https://zikalino.substack.com/p/getting-started-with-upcloud-using

  - type: section
    title: Prerequisites
    subitems:
      - $include: __docker_install_step.yaml
      - $include: __docker_start_step.yaml


footer:
  - type: footer
    id: footer
    subitems:
      - type: button
        id: install_button
        codicon: run-all
